#ifndef _MODULE_RESULTS_UI_
#define _MODULE_RESULTS_UI_

#define BASE_ALL_RECT_X 0
#define BASE_ALL_RECT_Y 0
#define BASE_ALL_RECT_W WINDOW_WIDTH
#define BASE_ALL_RECT_H WINDOW_HEIGHT
#define BASE_ALL_RECT SDL_Rect{ BASE_ALL_RECT_X, BASE_ALL_RECT_Y, BASE_ALL_RECT_W, BASE_ALL_RECT_H }

#define BASE_RECT_W (int)(640 * WINDOW_SCALE)
#define BASE_RECT_H (int)(160 * WINDOW_SCALE)
#define BASE_RECT_X 0
#define BASE_RECT_Y (WINDOW_HEIGHT - BASE_RECT_H)
#define BASE_RECT SDL_Rect{ BASE_RECT_X, BASE_RECT_Y, BASE_RECT_W, BASE_RECT_H }

#define GRID_RECT_Y (int)(56 * WINDOW_SCALE)
#define GRID_RECT_W (int)(276 * WINDOW_SCALE)
#define GRID_RECT_H (int)(292 * WINDOW_SCALE)

#define GRID_0_RECT_X (int)(38 * WINDOW_SCALE)
#define GRID_0_RECT SDL_Rect{ GRID_0_RECT_X, GRID_RECT_Y, GRID_RECT_W, GRID_RECT_H }

#define GRID_1_RECT_X (int)(330 * WINDOW_SCALE)
#define GRID_1_RECT SDL_Rect{ GRID_1_RECT_X, GRID_RECT_Y, GRID_RECT_W, GRID_RECT_H }

#define RESULTS_POSITION_SCALE (1.25f * WINDOW_SCALE)
#define RESULTS_POSITION_X (int)(0.5f * WINDOW_WIDTH)
#define RESULTS_POSITION_Y (int)(0.0225f * WINDOW_HEIGHT)
#define RESULTS_POSITION WindowPosition{ RESULTS_POSITION_X, RESULTS_POSITION_Y }

#define RESULT_POSITION_SCALE_W (1.25f * WINDOW_SCALE)
#define RESULT_POSITION_SCALE_H (0.75f * WINDOW_SCALE)
#define RESULT_POSITION_Y (int)(95 * WINDOW_SCALE)
#define RESULT_POSITION_H (int)(32 * WINDOW_SCALE)
#define RESULT_0_0_POSITION_X (int)(86 * WINDOW_SCALE)
#define RESULT_0_1_POSITION_X (int)(222 * WINDOW_SCALE)
#define RESULT_1_0_POSITION_X (int)(378 * WINDOW_SCALE)
#define RESULT_1_1_POSITION_X (int)(514 * WINDOW_SCALE)

#define RANK_TIME_POSITION_SCALE_W (1.25f * WINDOW_SCALE)
#define RANK_TIME_POSITION_SCALE_H (0.75f * WINDOW_SCALE)
#define RANK_TIME_POSITION_Y (int)(63 * WINDOW_SCALE)
#define RANK_0_POSITION_X (int)(86 * WINDOW_SCALE)
#define TIME_0_POSITION_X (int)(222 * WINDOW_SCALE)
#define RANK_1_POSITION_X (int)(378 * WINDOW_SCALE)
#define TIME_1_POSITION_X (int)(514 * WINDOW_SCALE)
#define RANK_0_POSITION WindowPosition{ RANK_0_POSITION_X, RANK_TIME_POSITION_Y }
#define TIME_0_POSITION WindowPosition{ TIME_0_POSITION_X, RANK_TIME_POSITION_Y }
#define RANK_1_POSITION WindowPosition{ RANK_1_POSITION_X, RANK_TIME_POSITION_Y }
#define TIME_1_POSITION WindowPosition{ TIME_1_POSITION_X, RANK_TIME_POSITION_Y }

#define CAR_VELOCITY (2000.0f * WINDOW_SCALE)
#define CAR_START_SCALE (0.0f * WINDOW_SCALE)
#define CAR_END_SCALE (10.0f * WINDOW_SCALE)
#define TIME_BETWEEN_CARS 4.0f
#define CAR_START_POSITION_X (int)(50 * WINDOW_SCALE)
#define CAR_START_POSITION_Y (int)(402 * WINDOW_SCALE)
#define CAR_END_POSITION_X (CAR_START_POSITION_X + WINDOW_WIDTH)
#define CAR_END_POSITION_Y (int)(CAR_START_POSITION_Y + 1.25f * WINDOW_HEIGHT)
#define CAR_DIFF_X (CAR_END_POSITION_X - CAR_START_POSITION_X)
#define CAR_DIFF_Y (CAR_END_POSITION_Y - CAR_START_POSITION_Y)
#define CAR_DISTANCE sqrtf(CAR_DIFF_X * CAR_DIFF_X + CAR_DIFF_Y * CAR_DIFF_Y)
#define CAR_STEP_X (CAR_DIFF_X / CAR_DISTANCE)
#define CAR_STEP_Y (CAR_DIFF_Y / CAR_DISTANCE)

#endif