#ifndef _MODULE_FREE_PRACTICE_UI_
#define _MODULE_FREE_PRACTICE_UI_

#define FREE_PRACTICE_POSITION_SCALE (1.125f * WINDOW_SCALE)
#define FREE_PRACTICE_POSITION_X (int)(0.9125f * WINDOW_WIDTH)
#define FREE_PRACTICE_POSITION_Y (int)(0.02f * WINDOW_HEIGHT)
#define FREE_PRACTICE_POSITION WindowPosition{ FREE_PRACTICE_POSITION_X, FREE_PRACTICE_POSITION_Y }

#define FREE_PRACTICE_FLAG_0_RECT_X (int)(0.9125f * WINDOW_WIDTH)
#define FREE_PRACTICE_FLAG_0_RECT_Y (int)(0.0175f * WINDOW_HEIGHT)
#define FREE_PRACTICE_FLAG_0_RECT_W (int)(1.25f * 40 * WINDOW_SCALE)
#define FREE_PRACTICE_FLAG_0_RECT_H (int)(1.25f * 28 * WINDOW_SCALE)
#define FREE_PRACTICE_FLAG_0_RECT SDL_Rect{ FREE_PRACTICE_FLAG_0_RECT_X, FREE_PRACTICE_FLAG_0_RECT_Y, FREE_PRACTICE_FLAG_0_RECT_W, FREE_PRACTICE_FLAG_0_RECT_H }

#define FREE_PRACTICE_FLAG_1_RECT_X (int)(0.4575f * WINDOW_WIDTH)
#define FREE_PRACTICE_FLAG_1_RECT_Y (int)(0.0175f * WINDOW_HEIGHT)
#define FREE_PRACTICE_FLAG_1_RECT_W (int)(1.25f * 40 * WINDOW_SCALE)
#define FREE_PRACTICE_FLAG_1_RECT_H (int)(1.25f * 28 * WINDOW_SCALE)
#define FREE_PRACTICE_FLAG_1_RECT SDL_Rect{ FREE_PRACTICE_FLAG_1_RECT_X, FREE_PRACTICE_FLAG_1_RECT_Y, FREE_PRACTICE_FLAG_1_RECT_W, FREE_PRACTICE_FLAG_1_RECT_H }

#endif