#ifndef _MODULE_ABOUT_UI_
#define _MODULE_ABOUT_UI_

#define BASE_ALL_RECT_X 0
#define BASE_ALL_RECT_Y 0
#define BASE_ALL_RECT_W WINDOW_WIDTH
#define BASE_ALL_RECT_H WINDOW_HEIGHT
#define BASE_ALL_RECT SDL_Rect{ BASE_ALL_RECT_X, BASE_ALL_RECT_Y, BASE_ALL_RECT_W, BASE_ALL_RECT_H }

#define CAR_RECT_X (int)(0.55f * WINDOW_WIDTH)
#define CAR_RECT_Y (int)(0.3f * WINDOW_HEIGHT)
#define CAR_RECT_W (int)(0.75f * 342 * WINDOW_SCALE)
#define CAR_RECT_H (int)(0.75f * 92 * WINDOW_SCALE)
#define CAR_RECT SDL_Rect{ CAR_RECT_X, CAR_RECT_Y, CAR_RECT_W, CAR_RECT_H }

#define ABOUT_POSITION_SCALE (1.25f * WINDOW_SCALE)
#define ABOUT_POSITION_X (int)(0.5f * WINDOW_WIDTH)
#define ABOUT_POSITION_Y (int)(0.055f * WINDOW_HEIGHT)
#define ABOUT_POSITION WindowPosition{ ABOUT_POSITION_X, ABOUT_POSITION_Y }

#define POSITION_SCALE WINDOW_SCALE
#define VALUE_POSITION_SCALE (0.75f * WINDOW_SCALE)
#define POSITION_X (int)(0.05f * WINDOW_WIDTH)
#define VALUE_POSITION_X (int)(0.3f * WINDOW_WIDTH)

#define PROJECT_POSITION_Y (int)(0.22f * WINDOW_HEIGHT)
#define PROJECT_POSITION WindowPosition{ POSITION_X, PROJECT_POSITION_Y }
#define PROJECT_VALUE_POSITION WindowPosition{ VALUE_POSITION_X, PROJECT_POSITION_Y }

#define TECH_POSITION_Y (int)(0.32f * WINDOW_HEIGHT)
#define TECH_POSITION WindowPosition{ POSITION_X, TECH_POSITION_Y }
#define TECH_VALUE_POSITION WindowPosition{ VALUE_POSITION_X, TECH_POSITION_Y }

#define AUTHOR_POSITION_Y (int)(0.42f * WINDOW_HEIGHT)
#define AUTHOR_POSITION WindowPosition{ POSITION_X, AUTHOR_POSITION_Y }
#define AUTHOR_VALUE_POSITION WindowPosition{ VALUE_POSITION_X, AUTHOR_POSITION_Y }

#define SEPARATION_POSITION_X (int)(0.5f * WINDOW_WIDTH)
#define SEPARATION_POSITION_Y (int)(0.52f * WINDOW_HEIGHT)
#define SEPARATION_POSITION WindowPosition{ SEPARATION_POSITION_X, SEPARATION_POSITION_Y }

#define CONTROLS_POSITION_Y_0 (int)(0.62f * WINDOW_HEIGHT)
#define CONTROLS_POSITION_Y_1 (int)(0.72f * WINDOW_HEIGHT)
#define CONTROLS_POSITION_Y_2 (int)(0.82f * WINDOW_HEIGHT)
#define CONTROLS_POSITION_Y_3 (int)(0.92f * WINDOW_HEIGHT)
#define CONTROLS_POSITION WindowPosition{ POSITION_X, CONTROLS_POSITION_Y_0 }
#define CONTROLS_VALUE_POSITION_0 WindowPosition{ VALUE_POSITION_X, CONTROLS_POSITION_Y_0 }
#define CONTROLS_VALUE_POSITION_1 WindowPosition{ VALUE_POSITION_X, CONTROLS_POSITION_Y_1 }
#define CONTROLS_VALUE_POSITION_2 WindowPosition{ VALUE_POSITION_X, CONTROLS_POSITION_Y_2 }
#define CONTROLS_VALUE_POSITION_3 WindowPosition{ VALUE_POSITION_X, CONTROLS_POSITION_Y_3 }

#endif