#ifndef _MODULE_COURSE_SELECT_UI_
#define _MODULE_COURSE_SELECT_UI_

#define BASE_RECT_X 0
#define BASE_RECT_Y 0
#define BASE_RECT_W WINDOW_WIDTH
#define BASE_RECT_H WINDOW_HEIGHT
#define BASE_RECT SDL_Rect{ BASE_RECT_X, BASE_RECT_Y, BASE_RECT_W, BASE_RECT_H }

#define COURSE_RECT_X (int)(112 * WINDOW_SCALE)
#define COURSE_RECT_Y (int)(96 * WINDOW_SCALE)
#define COURSE_RECT_W (int)(112 * WINDOW_SCALE)
#define COURSE_RECT_H (int)(176 * WINDOW_SCALE)
#define COURSE_RECT SDL_Rect{ COURSE_RECT_X, COURSE_RECT_Y, COURSE_RECT_W, COURSE_RECT_H }

#define COURSE_BACKGROUND_REGION_X 208
#define COURSE_BACKGROUND_REGION_Y 72

#define BACKGROUND_RECT_X (int)(112 * WINDOW_SCALE)
#define BACKGROUND_RECT_Y (int)(288 * WINDOW_SCALE)
#define BACKGROUND_RECT_W (int)(416 * WINDOW_SCALE)
#define BACKGROUND_RECT_H (int)(144 * WINDOW_SCALE)
#define BACKGROUND_RECT SDL_Rect{ BACKGROUND_RECT_X, BACKGROUND_RECT_Y, BACKGROUND_RECT_W, BACKGROUND_RECT_H }

#define COURSE_INFO_X (int)(256 * WINDOW_SCALE)
#define COURSE_INFO_VALUE_POSITION_SCALE_W (1.25f * WINDOW_SCALE)
#define COURSE_INFO_VALUE_POSITION_SCALE_H (0.75f * WINDOW_SCALE)

#define COURSE_NAME_POSITION_SCALE (1.5f * WINDOW_SCALE)
#define COURSE_NAME_POSITION_Y (int)(96 * WINDOW_SCALE)
#define COURSE_NAME_POSITION WindowPosition{ COURSE_INFO_X, COURSE_NAME_POSITION_Y }

#define COURSE_ROUND_POSITION_Y (int)(160 * WINDOW_SCALE)
#define COURSE_ROUND_POSITION WindowPosition{ COURSE_INFO_X, COURSE_ROUND_POSITION_Y }

#define COURSE_ROUND_VALUE_POSITION_X (int)(456 * WINDOW_SCALE)
#define COURSE_ROUND_VALUE_POSITION_Y (int)(160 * WINDOW_SCALE)
#define COURSE_ROUND_VALUE_POSITION WindowPosition{ COURSE_ROUND_VALUE_POSITION_X, COURSE_ROUND_VALUE_POSITION_Y }

#define COURSE_LENGTH_POSITION_Y (int)(200 * WINDOW_SCALE)
#define COURSE_LENGTH_POSITION WindowPosition{ COURSE_INFO_X, COURSE_LENGTH_POSITION_Y }

#define COURSE_LENGTH_VALUE_POSITION_X (int)(408 * WINDOW_SCALE)
#define COURSE_LENGTH_VALUE_POSITION_Y (int)(200 * WINDOW_SCALE)
#define COURSE_LENGTH_VALUE_POSITION WindowPosition{ COURSE_LENGTH_VALUE_POSITION_X, COURSE_LENGTH_VALUE_POSITION_Y }

#define COURSE_BEST_LAP_TIME_POSITION_Y (int)(240 * WINDOW_SCALE)
#define COURSE_BEST_LAP_TIME_POSITION WindowPosition{ COURSE_INFO_X, COURSE_BEST_LAP_TIME_POSITION_Y }

#define COURSE_BEST_LAP_TIME_VALUE_POSITION_X (int)(448 * WINDOW_SCALE)
#define COURSE_BEST_LAP_TIME_VALUE_POSITION_Y (int)(240 * WINDOW_SCALE)
#define COURSE_BEST_LAP_TIME_VALUE_POSITION WindowPosition{ COURSE_BEST_LAP_TIME_VALUE_POSITION_X, COURSE_BEST_LAP_TIME_VALUE_POSITION_Y }

#define COURSE_CHANGE_ANIMATION_N_R 11
#define COURSE_CHANGE_ANIMATION_N_C 7

#define BACKGROUND_CHANGE_ANIMATION_N_R 9
#define BACKGROUND_CHANGE_ANIMATION_N_C 26

#endif