#ifndef _MODULE_SUPER_MONACO_GP_UI_
#define _MODULE_SUPER_MONACO_GP_UI_

#include "Globals.h"

#define LAP_TIMES_POSITION_SCALE (1.0f * WINDOW_SCALE)
#define LAP_TIMES_POSITION_X (int)(0.0175f * WINDOW_WIDTH)
#define LAP_TIMES_POSITION_Y (int)(0.3275f * WINDOW_HEIGHT)
#define LAP_TIMES_POSITION WindowPosition{ LAP_TIMES_POSITION_X, LAP_TIMES_POSITION_Y }

#define LAP_TIMES_VALUE_POSITION_SCALE (0.85f * WINDOW_SCALE)
#define LAP_TIMES_VALUE_POSITION_Y (int)(0.425f * WINDOW_HEIGHT)
#define LAP_TIMES_VALUE_POSITION_H (int)(30 * WINDOW_SCALE)

#define POSITION_POSITION_SCALE WINDOW_SCALE
#define POSITION_POSITION_X (int)(0.6575f * WINDOW_WIDTH)
#define POSITION_POSITION_Y (int)(0.0225f * WINDOW_HEIGHT)
#define POSITION_POSITION WindowPosition{ POSITION_POSITION_X, POSITION_POSITION_Y }

#define POSITION_VALUE_POSITION_SCALE (2.0f * WINDOW_SCALE)
#define POSITION_VALUE_POSITION_X (int)(0.925f * WINDOW_WIDTH)
#define POSITION_VALUE_POSITION_Y (int)(0.0225f * WINDOW_HEIGHT)
#define POSITION_VALUE_POSITION WindowPosition{ POSITION_VALUE_POSITION_X, POSITION_VALUE_POSITION_Y }

#define CURRENT_LAP_POSITION_SCALE (1.0f * WINDOW_SCALE)
#define CURRENT_LAP_POSITION_X (int)(0.1f * WINDOW_WIDTH)
#define CURRENT_LAP_POSITION_Y (int)(0.3275f * WINDOW_HEIGHT)
#define CURRENT_LAP_POSITION WindowPosition{ CURRENT_LAP_POSITION_X, CURRENT_LAP_POSITION_Y }

/* #define CURRENT_LAP_VALUE_POSITION_SCALE (1.5f * WINDOW_SCALE)
#define CURRENT_LAP_VALUE_POSITION_X (int)(0.925f * WINDOW_WIDTH)
#define CURRENT_LAP_VALUE_POSITION_Y (int)(0.3275f * WINDOW_HEIGHT)
#define CURRENT_LAP_VALUE_POSITION WindowPosition{ CURRENT_LAP_VALUE_POSITION_X, CURRENT_LAP_VALUE_POSITION_Y } */

#endif